language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "hotiadiallo"
    token:
      secure: "a04ed26cc675e75f94b2219cd42cd45bbe1a6614"
script:
  - mvn --batch-mode --file ./src/pom.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
