language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "hotiadiallo"
    token:
      secure: "cb53c4298a2392830e30cc6439746b26e7e6ae2d"
script:
#  - mvn --batch-mode --file ./src/pom.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -P test-consumer,test-business -Dsonar.projectKey=hotiaDiallo_Java-Tests-Dev
  - mvn --batch-mode --file ./src/pom.xml clean package -P test-consumer,test-business
